n('<leader>gg', ':Git<cr> :winc L<cr>')
n('<leader>gd', ':Gdiff<cr>')
n('<leader>gp', ':Git pull --rebase<cr>')
n('<leader>gP', ':Git push<cr>')
n('<leader>gr', ':Gread<cr>')
n('<leader>gw', ':Gwrite<cr>')
n('<leader>ge', ':Gedit<cr>')
n('<leader>ga', ':Git add -p %<cr>')
n('<leader>gh', ':help fugitive<cr>')
n('<leader>gb', ':Git checkout<Space>')
n('<leader>gB', ':Git checkout -b<Space>')
