local mark = require("harpoon.mark")
local ui = require("harpoon.ui")

vim.keymap.set("n", "<Leader>mm", mark.add_file)
vim.keymap.set("n", "<Leader>MM", ui.toggle_quick_menu)
vim.keymap.set("n", "<Leader>mf", function() ui.nav_file(1) end)
vim.keymap.set("n", "<Leader>md", function() ui.nav_file(2) end)
vim.keymap.set("n", "<Leader>ms", function() ui.nav_file(3) end)
vim.keymap.set("n", "<Leader>ma", function() ui.nav_file(4) end)
vim.keymap.set("n", "<Leader>mj", function() ui.nav_file(5) end)
vim.keymap.set("n", "<Leader>mk", function() ui.nav_file(6) end)
vim.keymap.set("n", "<Leader>ml", function() ui.nav_file(7) end)
vim.keymap.set("n", "<Leader>m;", function() ui.nav_file(8) end)
